# Generated by Django 4.2.13 on 2024-05-23 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('typ', models.IntegerField(default=0)),
                ('art', models.CharField(max_length=100)),
                ('standorttyp', models.CharField(blank=True, max_length=50, null=True)),
                ('bezeichnung', models.CharField(blank=True, max_length=150, null=True)),
                ('bezeichnungzusatz', models.CharField(blank=True, max_length=150, null=True)),
                ('kurzbezeichnung', models.CharField(blank=True, max_length=150, null=True)),
                ('strasse', models.CharField(blank=True, max_length=150, null=True)),
                ('plz', models.CharField(blank=True, max_length=150, null=True)),
                ('ort', models.CharField(blank=True, max_length=150, null=True)),
                ('telefon', models.CharField(blank=True, max_length=150, null=True)),
                ('fax', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('profile', models.CharField(blank=True, max_length=150, null=True)),
                ('sprachen', models.CharField(blank=True, max_length=150, null=True)),
                ('www', models.URLField(blank=True, null=True)),
                ('traeger', models.CharField(blank=True, max_length=150, null=True)),
                ('traegertyp', models.IntegerField(default=0)),
                ('bezugnr', models.CharField(blank=True, max_length=150, null=True)),
                ('gebietsartnummer', models.IntegerField()),
                ('snummer', models.IntegerField(default=0)),
                ('nummer', models.IntegerField(default=0)),
                ('global_id', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.DecimalField(decimal_places=40, max_digits=50)),
                ('long', models.DecimalField(decimal_places=40, max_digits=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
