# Generated by Django 4.2.13 on 2024-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_school_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='bezeichnungzusatz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='kurzbezeichnung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.DecimalField(decimal_places=60, max_digits=70),
        ),
        migrations.AlterField(
            model_name='school',
            name='long',
            field=models.DecimalField(decimal_places=60, max_digits=70),
        ),
        migrations.AlterField(
            model_name='school',
            name='strasse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='www',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
