# Generated by Django 4.2.13 on 2024-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_alter_school_bezeichnungzusatz_alter_school_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
